//! 项目级状态写入 shim（D27）：hook 与 oma 二进制解耦。oma init 把自包含
//! 脚本部署到 `<project>\.oma\hooks\`（Windows = cmd、Linux = bash、
//! mac = zsh，用户裁 2026-09-10），各家 hook 注册指向 shim——state 通道
//! 零 oma 依赖，oma 可任意时刻无痛升级轮换。secretguard 由 shim fail-open
//! 委托：PreToolUse / UserPromptSubmit 时 oma 在位则转发 payload 并透传
//! 退出码（2 = block），不在位则放行（state 已写）。
//! `oma hook` 保留为手动入口与委托目标（含完整 notification 形状解析）。
//! cmd 形态两级（用户裁 2026-09-10：jq 归 ome 部署，shim 部署前探 PATH）：
//! jq 在位用 jq 解析（转义免疫、ts 取 jq now），缺位回落 findstr 硬解析并
//! warn 指向 `ome install jq`。sh 侧 sed 是 POSIX 基线不引依赖。

/// Windows cmd shim，jq 形态（首选）。约定：`%1` = agent 名；stdin = hook
/// payload JSON；项目根 = shim 自身位置上一级（`<root>\.oma\hooks\`）；
/// OHMYAGENTS_STATE_FILE 覆盖优先。字段提取与 state JSON 生成都走 jq：
/// `--arg` 传值让 jq 程序体内零双引号，绕开 cmd 引号地狱；ts 用 `now|floor`
/// 取纪元秒（locale 无关）。guard 委托前 payload 留在临时文件。
pub const STATE_CMD_JQ: &str = r#"@echo off
rem generated by oma init; rerun oma init to sync (D27 state shim, jq form)
setlocal EnableDelayedExpansion
set "AGENT=%~1"
if "%AGENT%"=="" exit /b 0
set "TMPF=%TEMP%\oma-state-%RANDOM%%RANDOM%.json"
more > "%TMPF%" 2>nul
set "ERAW="
for /f "usebackq delims=" %%a in (`jq -r ".hook_event_name // .hookEventName // empty" "%TMPF%" 2^>nul`) do (
  if not defined ERAW set "ERAW=%%a"
)
set "SID="
for /f "usebackq delims=" %%b in (`jq -r ".session_id // empty" "%TMPF%" 2^>nul`) do (
  if not defined SID set "SID=%%b"
)
set "STATE=unknown"
if /i "!ERAW!"=="SessionStart" set "STATE=idle"
if /i "!ERAW!"=="Stop" set "STATE=idle"
if /i "!ERAW!"=="SessionEnd" set "STATE=idle"
if /i "!ERAW!"=="Interrupt" set "STATE=idle"
if /i "!ERAW!"=="UserPromptSubmit" set "STATE=working"
if /i "!ERAW!"=="PreToolUse" set "STATE=working"
if /i "!ERAW!"=="PostToolUse" set "STATE=working"
if /i "!ERAW!"=="PostToolUseFailure" set "STATE=working"
if /i "!ERAW!"=="SubagentStart" set "STATE=working"
if /i "!ERAW!"=="SubagentStop" set "STATE=working"
if /i "!ERAW!"=="PreCompact" set "STATE=working"
if /i "!ERAW!"=="PermissionResult" set "STATE=working"
if /i "!ERAW!"=="PermissionRequest" set "STATE=blocked"
if /i "!ERAW!"=="Notification" (
  set "STATE=unknown"
  jq -e --arg k permission "(.notification_type // .notificationType // .matcher // .message // empty) | tostring | contains($k)" "%TMPF%" >nul 2>nul && set "STATE=blocked"
)
set "TARGET="
if defined OHMYAGENTS_STATE_FILE set "TARGET=%OHMYAGENTS_STATE_FILE%"
if not defined TARGET set "TARGET=%~dp0..\state\%AGENT%.json"
for %%d in ("!TARGET!") do if not exist "%%~fd\.." mkdir "%%~fd\.." 2>nul
jq -n --arg state "!STATE!" --arg event "!ERAW!" --arg agent "%AGENT%" --arg session "!SID!" "{state:$state,event:$event,agent:$agent,session:$session,ts:(now|floor)}" > "!TARGET!"
if /i "!ERAW!"=="PreToolUse" goto guard
if /i "!ERAW!"=="UserPromptSubmit" goto guard
del "%TMPF%" >nul 2>nul
exit /b 0
:guard
where oma >nul 2>nul
if errorlevel 1 (
  del "%TMPF%" >nul 2>nul
  exit /b 0
)
type "%TMPF%" | oma hook --agent %AGENT%
set "RC=%errorlevel%"
del "%TMPF%" >nul 2>nul
exit /b %RC%
"#;

/// Windows cmd shim，findstr 回落形态（jq 缺位时部署，warn 指向 ome install
/// jq）。同约定；解析是锚定子串替换（`*hook_event_name":=` 剥前缀再取首
/// 引号段），比 token 位次硬切抗字段序变化、不造伪值；grok 的 camelCase
/// 事件名在此形态降级 unknown（jq 形态才解析）。ts 记 0（状态栏不消费 ts）。
pub const STATE_CMD: &str = r#"@echo off
rem generated by oma init; rerun oma init to sync (D27 state shim, findstr fallback)
setlocal EnableDelayedExpansion
set "AGENT=%~1"
if "%AGENT%"=="" exit /b 0
set "TMPF=%TEMP%\oma-state-%RANDOM%%RANDOM%.json"
more > "%TMPF%" 2>nul
set "ELINE="
for /f "usebackq delims=" %%l in (`findstr /c:"hook_event_name" "%TMPF%" 2^>nul`) do (
  if not defined ELINE set "ELINE=%%l"
)
set "ERAW="
if defined ELINE (
  set ERAW=!ELINE:*hook_event_name":=!
  set ERAW=!ERAW:"=,!
  for /f "tokens=1 delims=," %%a in ("!ERAW!") do set "ERAW=%%a"
)
set "SLINE="
for /f "usebackq delims=" %%m in (`findstr /c:"session_id" "%TMPF%" 2^>nul`) do (
  if not defined SLINE set "SLINE=%%m"
)
set "SID="
if defined SLINE (
  set SID=!SLINE:*session_id":=!
  set SID=!SID:"=,!
  for /f "tokens=1 delims=," %%b in ("!SID!") do set "SID=%%b"
)
set "STATE=unknown"
if /i "!ERAW!"=="SessionStart" set "STATE=idle"
if /i "!ERAW!"=="Stop" set "STATE=idle"
if /i "!ERAW!"=="SessionEnd" set "STATE=idle"
if /i "!ERAW!"=="Interrupt" set "STATE=idle"
if /i "!ERAW!"=="UserPromptSubmit" set "STATE=working"
if /i "!ERAW!"=="PreToolUse" set "STATE=working"
if /i "!ERAW!"=="PostToolUse" set "STATE=working"
if /i "!ERAW!"=="PostToolUseFailure" set "STATE=working"
if /i "!ERAW!"=="SubagentStart" set "STATE=working"
if /i "!ERAW!"=="SubagentStop" set "STATE=working"
if /i "!ERAW!"=="PreCompact" set "STATE=working"
if /i "!ERAW!"=="PermissionResult" set "STATE=working"
if /i "!ERAW!"=="PermissionRequest" set "STATE=blocked"
if /i "!ERAW!"=="Notification" (
  set "STATE=unknown"
  findstr /c:"permission" "%TMPF%" >nul 2>nul && set "STATE=blocked"
)
set "TARGET="
if defined OHMYAGENTS_STATE_FILE set "TARGET=%OHMYAGENTS_STATE_FILE%"
if not defined TARGET set "TARGET=%~dp0..\state\%AGENT%.json"
for %%d in ("!TARGET!") do if not exist "%%~fd\.." mkdir "%%~fd\.." 2>nul
>"!TARGET!" echo {"state":"!STATE!","event":"!ERAW!","agent":"%AGENT%","session":"!SID!","ts":0}
if /i "!ERAW!"=="PreToolUse" goto guard
if /i "!ERAW!"=="UserPromptSubmit" goto guard
del "%TMPF%" >nul 2>nul
exit /b 0
:guard
where oma >nul 2>nul
if errorlevel 1 (
  del "%TMPF%" >nul 2>nul
  exit /b 0
)
type "%TMPF%" | oma hook --agent %AGENT%
set "RC=%errorlevel%"
del "%TMPF%" >nul 2>nul
exit /b %RC%
"#;

/// POSIX sh shim（Linux = bash、mac = zsh 同一语义；shebang 由部署侧按宿主
/// 写 bash 或 zsh）。`$1` = agent；stdin = payload；ts 取纪元秒。sed 是
/// POSIX 基线（jq 不作 Unix 前置依赖）。
pub const STATE_SH: &str = r#"#!/usr/bin/env bash
# generated by oma init; rerun oma init to sync (D27 state shim)
agent="${1:-}"
[ -n "$agent" ] || exit 0
payload="$(cat)"
raw="$(printf '%s' "$payload" | sed -n 's/.*"hook[_]event[_]name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p;t')"
[ -n "$raw" ] || raw="$(printf '%s' "$payload" | sed -n 's/.*"hookEventName"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p;t')"
event="$(printf '%s' "$raw" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]')"
sid="$(printf '%s' "$payload" | sed -n 's/.*"session[_]id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p;t')"
case "$event" in
  sessionstart|stop|sessionend|interrupt|idle) state=idle ;;
  userpromptsubmit|userpromptuse|pretooluse|posttooluse|posttoolusefailure|subagentstart|subagentstop|precompact|permissionresult|working) state=working ;;
  permissionrequest|blocked|elicitation|elicitationresult) state=blocked ;;
  notification)
    state=unknown
    case "$payload" in *permission*) state=blocked ;; esac
    ;;
  *) state=unknown ;;
esac
if [ -n "$OHMYAGENTS_STATE_FILE" ]; then
  target="$OHMYAGENTS_STATE_FILE"
else
  shim_dir="$(cd "$(dirname "$0")" && pwd)"
  root="$(cd "$shim_dir/../.." && pwd)"
  target="$root/.oma/state/$agent.json"
  mkdir -p "$(dirname "$target")"
fi
ts="$(date +%s)"
printf '{"state":"%s","event":"%s","agent":"%s","session":"%s","ts":%s}\n' \
  "$state" "$event" "$agent" "$sid" "$ts" > "$target"
case "$event" in
  pretooluse|userpromptsubmit)
    if command -v oma >/dev/null 2>&1; then
      printf '%s' "$payload" | oma hook --agent "$agent"
      exit $?
    fi
    ;;
esac
exit 0
"#;

/// 部署时替换 shebang 行得到 zsh 变体（语义同 bash 形；zsh 无 bashisms 可用
/// 之处已避开，dirname/date/sed/case 全兼容）。
pub fn state_sh_for(shell: &str) -> String {
    let body = STATE_SH.trim_start_matches("#!/usr/bin/env bash\n");
    format!("#!/usr/bin/env {shell}\n{body}")
}

/// Windows grok 包装（M048 形态：grok 的 command 必须是可整串 spawn 的单
/// 路径，参数不传；把 grok 烧进包装再转主 shim）。
pub const STATE_GROK_CMD: &str = "@echo off\r\nrem generated by oma init; rerun oma init to sync (D27 grok wrapper)\r\n\"%~dp0oma-state.cmd\" grok\r\nexit /b %errorlevel%\r\n";

/// CRLF 规整（cmd 批处理对 LF-only 的 goto/label 扫描有历史坑；统一落 CRLF）。
fn crlf(s: &str) -> String {
    s.replace("\r\n", "\n").replace('\n', "\r\n")
}

/// 写前比对：内容相同不重写（幂等；report.wrote 只记实写）。
fn write_if_changed(path: &std::path::Path, content: &str) -> Result<bool, String> {
    if std::fs::read_to_string(path)
        .map(|old| old == content)
        .unwrap_or(false)
    {
        return Ok(false);
    }
    std::fs::write(path, content).map_err(|e| format!("{}: {e}", path.display()))?;
    Ok(true)
}

/// 部署 shim 文件集：三份脚本全侧落齐（跨 OS 共享项目并存：Windows init
/// 也备好 .sh、Unix init 也备好 .cmd；+x 只在 Unix 生效）。cmd 主 shim 按
/// jq 探测选形态（D27 用户裁定：jq 归 ome 部署，部署前探 PATH；缺位回落
/// findstr 版并 warn）。返回 (实写路径, 警告)。
pub fn deploy_shims(
    root: &std::path::Path,
) -> Result<(Vec<std::path::PathBuf>, Vec<String>), String> {
    use std::path::PathBuf;
    let dir = root.join(".oma").join("hooks");
    std::fs::create_dir_all(&dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    let mut wrote: Vec<PathBuf> = Vec::new();
    let mut warns = Vec::new();
    let cmd_body = if crate::pathutil::find_on_path("jq").is_some() {
        STATE_CMD_JQ.to_string()
    } else {
        warns.push(
            "jq not on PATH: state shim deployed findstr fallback; \
             ome install jq then rerun oma init to upgrade"
                .to_string(),
        );
        STATE_CMD.to_string()
    };
    let cmd = dir.join("oma-state.cmd");
    if write_if_changed(&cmd, &crlf(&cmd_body))? {
        wrote.push(cmd);
    }
    let grok = dir.join("oma-state-grok.cmd");
    if write_if_changed(&grok, &crlf(STATE_GROK_CMD))? {
        wrote.push(grok);
    }
    // 宿主 zsh 判定：macOS 缺 /usr/bin/bash 的兜底；两 shebang 皆兼容。
    let sh = dir.join("oma-state.sh");
    let sh_body = if cfg!(target_os = "macos") {
        state_sh_for("zsh")
    } else {
        state_sh_for("bash")
    };
    if write_if_changed(&sh, &sh_body)? {
        wrote.push(sh);
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(&sh, std::fs::Permissions::from_mode(0o755));
    }
    Ok((wrote, warns))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shims_carry_marker_and_platform_shebang() {
        for body in [STATE_CMD_JQ, STATE_CMD] {
            assert!(body.contains("generated by oma init"));
            // 默认落点：<root>\.oma\state\<agent>.json（shim 在 .oma\hooks\
            // 上一级回 .oma）。
            assert!(body.contains(r#"%~dp0..\state\"#), "default target wrong");
            assert!(body.contains("OHMYAGENTS_STATE_FILE"), "env override wins");
            assert!(body.contains("oma hook --agent"), "secretguard delegation");
            assert!(body.contains(":guard"), "guard label present");
        }
        // jq 形态专属：字段提取与 state JSON 生成都走 jq，ts 用 now|floor。
        assert!(STATE_CMD_JQ.contains(r#"jq -r ".hook_event_name"#));
        assert!(STATE_CMD_JQ.contains(r#"jq -r ".session_id"#));
        assert!(STATE_CMD_JQ.contains("jq -n --arg state"));
        assert!(STATE_CMD_JQ.contains("ts:(now|floor)"));
        assert!(!STATE_CMD_JQ.contains("findstr"), "jq form must not parse by hand");
        // 回落形态专属：findstr 硬解析、ts 记 0。
        assert!(STATE_CMD.contains("findstr"));
        assert!(STATE_CMD.contains("\"ts\":0"));
        // 程序体零裸双引号包 jq 字符串（cmd 引号地狱规避，--arg 传值）。
        assert!(!STATE_CMD_JQ.contains(r#""permission""#));
        assert!(STATE_GROK_CMD.contains("oma-state.cmd\" grok"));
        let zsh = state_sh_for("zsh");
        assert!(zsh.starts_with("#!/usr/bin/env zsh\n"));
        assert!(zsh.contains("date +%s"));
        let bash = state_sh_for("bash");
        assert!(bash.starts_with("#!/usr/bin/env bash\n"));
        // 四态表齐全（与 hook.rs map_event 对齐）。
        for s in ["idle", "working", "blocked", "unknown"] {
            assert!(zsh.contains(s), "state {s} missing");
        }
    }

    #[test]
    fn crlf_normalizes_without_doubling() {
        assert!(crlf("a\nb").contains("a\r\nb"));
        assert_eq!(crlf("a\r\nb"), "a\r\nb", "already-CRLF stays single");
    }

    #[test]
    fn write_if_changed_skips_identical_content() {
        let dir = std::env::temp_dir().join(format!(
            "oma-shim-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_millis()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let p = dir.join("x.cmd");
        assert!(write_if_changed(&p, "v1").unwrap());
        assert!(!write_if_changed(&p, "v1").unwrap(), "identical skips");
        assert!(write_if_changed(&p, "v2").unwrap());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn deploy_shims_writes_all_three_and_is_idempotent() {
        let dir = std::env::temp_dir().join(format!(
            "oma-shimdep-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_millis()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let (wrote, warns) = deploy_shims(&dir).unwrap();
        // 三份脚本全侧落齐（跨 OS 共享项目并存）。
        assert!(dir.join(".oma").join("hooks").join("oma-state.cmd").exists());
        assert!(
            dir
                .join(".oma")
                .join("hooks")
                .join("oma-state-grok.cmd")
                .exists()
        );
        assert!(dir.join(".oma").join("hooks").join("oma-state.sh").exists());
        // jq 探测结果与宿主环境一致：jq 在位无警告、落 jq 形态；缺位带警告、
        // 落 findstr 形态（期望来自同一探测原语，非被测逻辑镜像）。
        let jq_hit = crate::pathutil::find_on_path("jq").is_some();
        assert_eq!(warns.is_empty(), jq_hit);
        let cmd = std::fs::read_to_string(dir.join(".oma").join("hooks").join("oma-state.cmd"))
            .unwrap();
        assert!(cmd.contains("\r\n"), "cmd files land CRLF");
        assert_eq!(
            cmd.contains("jq form"),
            jq_hit,
            "jq presence must pick the jq variant"
        );
        assert_eq!(wrote.len(), 3, "first deploy writes three shim files");
        // 幂等：内容不变不重写。
        let (wrote2, _) = deploy_shims(&dir).unwrap();
        assert!(wrote2.is_empty(), "redeploy writes nothing: {wrote2:?}");
        let _ = std::fs::remove_dir_all(&dir);
    }
}
